update dev with new template
LNUc-EEMiS/metatdenovo pull request #51
Opened 2022-09-16 14:00 UTC by Danilo2771

## PR checklist

- [ ] This comment contains a description of changes (with reason).
- [ ] If you've fixed a bug or added code that should be tested, add tests!
    - [ ] If you've added a new tool - have you followed the pipeline conventions in the [contribution docs](https://github.com/nf-core/metatdenovo/tree/master/.github/CONTRIBUTING.md)
    - [ ] If necessary, also make a PR on the nf-core/metatdenovo _branch_ on the [nf-core/test-datasets](https://github.com/nf-core/test-datasets) repository.
- [ ] Make sure your code lints (`nf-core lint`).
- [ ] Ensure the test suite passes (`nextflow run . -profile test,docker`).
- [ ] Usage Documentation in `docs/usage.md` is updated.
- [ ] Output Documentation in `docs/output.md` is updated.
- [ ] `CHANGELOG.md` is updated.
- [ ] `README.md` is updated (including new tool citations and authors/contributors).

2022-09-20 06:59 UTC, erikrikarddaniel requested changes
A few mistakes.

2022-09-20 06:59 UTC, erikrikarddaniel commented on lib/NfcoreTemplate.groovy
> +                    "This will be dependent on your local compute enviroment but can be acheived via one or more of the following:\n" +
Funny if this is the updated template -- new spelling mistakes!?

2022-09-20 06:59 UTC, erikrikarddaniel commented on nextflow.config
> +
I can't see that we want this, we're not using igenomes.

2022-09-20 06:59 UTC, erikrikarddaniel commented on workflows/metatdenovo.nf
> +<<<<<<< HEAD
Merge conflict line.

2022-09-21 06:58 UTC, erikrikarddaniel commented
There's still a merge conflict in `modules.config` it seems.

2022-09-28 10:45 UTC, emnilsson approved these changes
LGTM

2022-09-28 12:32 UTC, merged